<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Core\Pango.Application\Pango.Application.csproj" />
	</ItemGroup>

</Project>
