<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="ErrorOr" />
	  <PackageReference Include="FluentValidation" />
	  <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
	  <PackageReference Include="Mapster" />
	  <PackageReference Include="Mapster.DependencyInjection" />
	  <PackageReference Include="MediatR" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	  <PackageReference Include="NaturalSort.Extension" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Pango.Domain\Pango.Domain.csproj" />
	</ItemGroup>
</Project>
