<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<AssemblyTitle>Pango</AssemblyTitle>
		<Product>Pango</Product>
		<Company>The Cats Lab</Company>
		<Copyright>Copyright © 2026 The Cats Lab</Copyright>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformVersion>10.0.18362.0</TargetPlatformVersion>
		<TargetPlatformMinVersion>10.0.18362.0</TargetPlatformMinVersion>
		<RootNamespace>Pango.Desktop.Uwp</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x86;x64;arm64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<PublishProfile>win-$(Platform).pubxml</PublishProfile>
		<UseWinUI>true</UseWinUI>
		<EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>
		<GenerateAppInstallerFile>False</GenerateAppInstallerFile>
		<AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
		<PackageCertificateThumbprint>679B96D3AF7C38D5E9EF9D648708703CDFA397A6</PackageCertificateThumbprint>
		<AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
		<AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
		<AppxSymbolPackageEnabled>False</AppxSymbolPackageEnabled>
		<GenerateTestArtifacts>True</GenerateTestArtifacts>
		<AppxBundle>Never</AppxBundle>
		<AppInstallerUri>D:\Projects\Pango\pango\src\Presentation\Desktop\Pango.Desktop.Uwp\AppPackages\Installer</AppInstallerUri>
		<HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<Title>Pango</Title>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
	  <NoWarn>CA1416;</NoWarn>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
	  <NoWarn>CA1416;</NoWarn>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|arm64'">
	  <NoWarn>CA1416;</NoWarn>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
	  <NoWarn>CA1416;</NoWarn>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
	  <NoWarn>CA1416;</NoWarn>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|arm64'">
	  <NoWarn>CA1416;</NoWarn>
	</PropertyGroup>
	
	<ItemGroup>
		<Content Include="Assets\folder.png" />
		<Content Include="Assets\LargeTile.scale-100.png" />
		<Content Include="Assets\LargeTile.scale-125.png" />
		<Content Include="Assets\LargeTile.scale-150.png" />
		<Content Include="Assets\LargeTile.scale-200.png" />
		<Content Include="Assets\LargeTile.scale-400.png" />
		<Content Include="Assets\logo.ico" />
		<Content Include="Assets\logo.png" />
		<Content Include="Assets\SmallTile.scale-100.png" />
		<Content Include="Assets\SmallTile.scale-125.png" />
		<Content Include="Assets\SmallTile.scale-150.png" />
		<Content Include="Assets\SmallTile.scale-200.png" />
		<Content Include="Assets\SmallTile.scale-400.png" />
		<Content Include="Assets\SplashScreen.scale-100.png" />
		<Content Include="Assets\SplashScreen.scale-125.png" />
		<Content Include="Assets\SplashScreen.scale-150.png" />
		<Content Include="Assets\SplashScreen.scale-400.png" />
		<Content Include="Assets\Square150x150Logo.scale-100.png" />
		<Content Include="Assets\Square150x150Logo.scale-125.png" />
		<Content Include="Assets\Square150x150Logo.scale-150.png" />
		<Content Include="Assets\Square150x150Logo.scale-400.png" />
		<Content Include="Assets\Square44x44Logo.altform-lightunplated_targetsize-16.png" />
		<Content Include="Assets\Square44x44Logo.altform-lightunplated_targetsize-24.png" />
		<Content Include="Assets\Square44x44Logo.altform-lightunplated_targetsize-256.png" />
		<Content Include="Assets\Square44x44Logo.altform-lightunplated_targetsize-32.png" />
		<Content Include="Assets\Square44x44Logo.altform-lightunplated_targetsize-48.png" />
		<Content Include="Assets\Square44x44Logo.altform-unplated_targetsize-16.png" />
		<Content Include="Assets\Square44x44Logo.altform-unplated_targetsize-256.png" />
		<Content Include="Assets\Square44x44Logo.altform-unplated_targetsize-32.png" />
		<Content Include="Assets\Square44x44Logo.altform-unplated_targetsize-48.png" />
		<Content Include="Assets\Square44x44Logo.scale-100.png" />
		<Content Include="Assets\Square44x44Logo.scale-125.png" />
		<Content Include="Assets\Square44x44Logo.scale-150.png" />
		<Content Include="Assets\Square44x44Logo.scale-400.png" />
		<Content Include="Assets\Square44x44Logo.targetsize-16.png" />
		<Content Include="Assets\Square44x44Logo.targetsize-24.png" />
		<Content Include="Assets\Square44x44Logo.targetsize-256.png" />
		<Content Include="Assets\Square44x44Logo.targetsize-32.png" />
		<Content Include="Assets\Square44x44Logo.targetsize-48.png" />
		<Content Include="Assets\StoreLogo.scale-100.png" />
		<Content Include="Assets\StoreLogo.scale-125.png" />
		<Content Include="Assets\StoreLogo.scale-150.png" />
		<Content Include="Assets\StoreLogo.scale-200.png" />
		<Content Include="Assets\StoreLogo.scale-400.png" />
		<Content Include="Assets\Wide310x150Logo.scale-100.png" />
		<Content Include="Assets\Wide310x150Logo.scale-125.png" />
		<Content Include="Assets\Wide310x150Logo.scale-150.png" />
		<Content Include="Assets\Wide310x150Logo.scale-400.png" />
		<Content Include="Assets\LockScreenLogo.scale-200.png" />
		<Content Include="Assets\SplashScreen.scale-200.png" />
		<Content Include="Assets\Square150x150Logo.scale-200.png" />
		<Content Include="Assets\Square44x44Logo.scale-200.png" />
		<Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
		<Content Include="Assets\Wide310x150Logo.scale-200.png" />
		<Content Include="Properties\launchSettings.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="CommunityToolkit.WinUI.Behaviors" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" />
		<PackageReference Include="H.NotifyIcon.WinUI" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" />
		<PackageReference Include="PInvoke.User32" />
		<PackageReference Include="Serilog.Extensions.Logging" />
		<PackageReference Include="Serilog.Sinks.File" />
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Core\Pango.Application\Pango.Application.csproj" />
		<ProjectReference Include="..\..\..\Core\Pango.Domain\Pango.Domain.csproj" />
		<ProjectReference Include="..\..\..\Infrastructure\Pango.Infrastructure\Pango.Infrastructure.csproj" />
		<ProjectReference Include="..\..\..\Infrastructure\Pango.Persistence.File\Pango.Persistence.File.csproj" />
		<ProjectReference Include="..\..\..\Services\Pango.BackupService\Pango.BackupService.csproj" />
	</ItemGroup>

	<!-- Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging Tools extension 
       to be activated for this project even if the Windows App SDK Nuget package has not yet been restored -->
	<ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnablePreviewMsixTooling)'=='true'">
		<ProjectCapability Include="Msix" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Package.appxmanifest">
			<SubType>Designer</SubType>
		</None>
		<None Include="Package.Dev.appxmanifest">
			<SubType>Designer</SubType>
		</None>
	</ItemGroup>
	
	<!-- Embed all "Resources.resw" files in the "Strings" folder to the output folder. -->
	<ItemGroup>
		<Content Include="Strings\**\*.resw">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
	  <None Remove="Assets\logo.ico" />
	  <None Remove="Dialogs\Views\ChangePasswordDialog.xaml" />
	  <None Remove="Dialogs\Views\ExportCompletedDialog.xaml" />
	  <None Remove="Dialogs\Views\ExportDialog.xaml" />
	  <None Remove="Dialogs\Views\GeneratePasswordDialog.xaml" />
	  <None Remove="Dialogs\Views\ImportDialog.xaml" />
	  <None Remove="Views\ExportImportView.xaml" />
	  <None Remove="Views\GeneratePasswordView.xaml" />
	</ItemGroup>
	<ItemGroup>
	  <None Include="..\..\..\..\LICENSE">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>
	<ItemGroup>
	  <Content Update="Assets\logo.ico">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Dialogs\Views\GeneratePasswordDialog.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Views\GeneratePasswordView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Dialogs\Views\ImportDialog.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Dialogs\Views\ExportCompletedDialog.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Dialogs\Views\ExportDialog.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Views\ExportImportView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Dialogs\Views\ChangePasswordDialog.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
</Project>